USE [Qualys]
GO

/****** Object:  Table [dbo].[Appliance]    Script Date: 8/11/2026 8:32:18 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ScanHistory](
	[DATETIME] [datetime] NOT NULL,
	[REF] [varchar](50) NOT NULL,
	[TYPE] [varchar](30) NOT NULL,
	[TITLE] [varchar](200) NOT NULL,
	[USER_LOGIN] [varchar](50) NOT NULL,
	[LAUNCH_DATETIME] [datetime] NOT NULL,
	[DURATION] [int] NOT NULL,
	[PROCESSING_PRIORITY] [varchar](50) NOT NULL,
	[PROCESSED] [int] NOT NULL,
 CONSTRAINT [PK_ScanHistory] PRIMARY KEY CLUSTERED 
(
	[DATETIME] ASC,
	[REF] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO